apiVersion: apps/v1
kind: Deployment
metadata:
  name: clicker-deployment
  namespace: app
  labels:
    app: clicker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clicker
  template:
    metadata:
      labels:
        app: clicker
    spec:
      containers:
      - name: clicker
        image: ghcr.io/randsw/k8s-altinity-click:latest
        ports:
        - containerPort: 8080
        env:
        - name: APP_PORT
          value: "8080"
        # Optional full ClickHouse URL, can be set via secret
        - name: CLICKHOUSE_HOST
          value: clickhouse-cart-clickhouse-cluster:9000
        # Added env vars for ClickHouse authentication
        - name: CLICKHOUSE_USER
          value: cart_user
        - name: CLICKHOUSE_DATABASE
          value: cart
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: click-credentials
              key: db-password
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
